[versions]
activityCompose = "1.9.3"
agp = "8.8.0"
coilVersion = "2.6.0"
composeBom = "2024.11.00"
coreKtx = "1.15.0"
generativeai = "0.9.0"
glance = "1.1.1"
hilt = "2.52"
hiltAndroidx = "1.2.0"
kotlin = "2.0.20"
kotlinSerialization = "1.7.1"
kotlinSerializationPlugin = "2.0.0"
kspPlugin = "2.0.20-1.0.25"
lifecycleRuntimeKtx = "2.8.7"
navigationCompose = "2.8.4"
retrofitKotlinX = "0.8.0"
retrofitVersion = "2.9.0"
splashscreen = "1.1.0-rc01"
work = "2.10.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coilVersion" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
glance-appwidget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "glance" }
glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }
glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "glance" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-compiler-androidx = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltAndroidx" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltAndroidx" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltAndroidx" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinSerialization" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
retrofit-kotlinx-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinX" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
work = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializationPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }

